version: 0.2

phases:
  pre_build:
    commands:
      - echo Entered the pre_build phase...
      - npm install
    finally:
      - echo Exiting pre_build phase...
  build:
    commands:
      - echo Entered the build phase...
      - echo Build started on `date`
      - npm run build
    finally:
      - echo Exiting build pahse...
  post_build:
    commands:
      - echo Entered the post_build phase...
      - echo Build completed on `date`
artifacts:
  files:
    - "**/*"
  base-directory: "out"
